#!/bin/bash

CFG_ENV_FILE=~/.local/lib/termux-vid-compression/.env

if [ ! -f $CFG_ENV_FILE ];then
    echo "Missing .env file in termux-vid-compression library."
    echo "It must contain target webdav url, a source path for your (compressed) videos and a target path for your videos!"
    echo "For this, specify the ENV Variables \"WEBDAV_URL\", \"VIDEO_LOCAl_SRC\" and \"VIDEO_REMOTE_TRG\"!"
    exit 1
fi

. $CFG_ENV_FILE

NETRC_CFG_FILE=~/.netrc
if [ ! -f $NETRC_CFG_FILE ];then
    echo "Missing .netrc file at \"$NETRC_CFG_FILE\"."
    echo "Use this to provide your credentials for your webdav server."
    echo "Add an entry with:"
    echo "\"machine <domain of your webdav url>\""
    echo "\"login <your webdav user>\""
    echo "\"password <your user's pw>\""
    exit 2
fi

set -u
. ~/.local/lib/termux-vid-compression/lib/webdav_sync
sync_local_w_remote $VIDEO_LOCAL_SRC $VIDEO_REMOTE_TRG

